import { contactEmail } from '@/content/company';

/**
 * Enquiry delivery: the Supabase record and the Resend notification.
 *
 * SERVER ONLY. This module reads a service-role credential and a mail API
 * credential from the environment. It must never be imported by a client
 * component. Three independent things stop those values reaching a browser, and
 * they are listed here rather than assumed:
 *
 *  1. Its only caller is `src/app/contact/actions.ts`, which is a `'use server'`
 *     module. Next.js compiles such a module to a server reference: the body
 *     never enters a client bundle, only an opaque action id does.
 *  2. None of the variable names below carries the `NEXT_PUBLIC_` prefix. Next
 *     inlines only prefixed variables into client code, so even if this module
 *     were dragged into a client bundle, the reads below would evaluate to
 *     `undefined` there rather than to a credential.
 *  3. The guard immediately below, which makes that mistake loud instead of
 *     silent. A dependency-free stand-in for the `server-only` package, which
 *     this project is not permitted to add.
 *
 * Points 1 and 2 are checked mechanically after each build: see
 * `CONTACT-FORM-SETUP.md`, "Proving nothing reaches the browser".
 *
 * NO TRANSPORT DEPENDENCY. Both providers are called over `fetch` against their
 * documented HTTP APIs rather than through their SDKs. See `DEPENDENCIES.md`,
 * entry 2026-09-14, for why - it is a decision with reasons, not an accident,
 * and it is reversible.
 */

if (typeof window !== 'undefined') {
  throw new Error(
    'src/lib/enquiries.ts was evaluated in a browser. It reads server-only ' +
      'credentials and must only ever be imported by server code.',
  );
}

/**
 * The handoff's section 14 "Form qualifier", in its order.
 *
 * The same four strings are the form's labels (`src/app/contact/ContactForm.tsx`)
 * and the homepage's "What we will ask" card (`src/app/page.tsx`). All three
 * must read identically. They live here now rather than in `actions.ts`,
 * because a `'use server'` module may export only async functions and this one
 * may export whatever it likes - but they are deliberately NOT imported by the
 * form, which is a client component and must not pull this module into the
 * browser bundle.
 */
const QUESTIONS = [
  ['objective', 'What are you trying to build or change?'],
  ['existing', 'What exists today?'],
  ['deadline', 'Is there a deadline?'],
  ['success', 'What would a successful result look like?'],
] as const;

/** One validated submission, exactly as the form collects it. */
export type Enquiry = {
  /**
   * Generated by the caller before delivery is attempted, so that the id in the
   * server log, the id in the database row and the reference in the
   * notification email are the same string. It is the only identifier that
   * appears in a log line, and it carries no personal data.
   */
  id: string;
  name: string;
  /** Optional fields arrive as `''` when unanswered, never as undefined. */
  company: string;
  email: string;
  objective: string;
  existing: string;
  deadline: string;
  success: string;
  source: string;
  /** ISO 8601. Used in the email body; the row's own `created_at` is the record. */
  receivedAt: string;
};

/**
 * What happened to one half of the delivery.
 *
 * `unconfigured` is kept distinct from `failed` because the two mean different
 * things to the visitor: one is a deployment that was never wired up, the other
 * is a provider that refused or timed out. The caller says something different
 * for each.
 */
export type LegStatus = 'unconfigured' | 'ok' | 'failed';

export type DeliveryOutcome = {
  store: LegStatus;
  email: LegStatus;
};

/** How long either provider gets before we stop waiting. */
const TIMEOUT_MS = 8000;

/* ------------------------------------------------------------------ logging */

/**
 * A provider's own short error code, and only if it really is one.
 *
 * Both providers return a body that mixes a machine code with free text:
 * PostgREST sends `{ code, message, details, hint }` and Resend sends
 * `{ name, message, statusCode }`. The free-text fields quote the data that
 * caused the error, which for this table means a visitor's name or email
 * address - so they must never reach a log.
 *
 * Rather than trusting a rule about which field to read, this function will
 * only return a value that is SHAPED like a code: short, and alphanumeric with
 * underscores. Anything else is discarded. A sentence cannot survive that test,
 * so a sentence cannot be logged, whatever a provider decides to put in these
 * fields in future.
 */
function safeCode(body: unknown): string {
  if (typeof body !== 'object' || body === null) return 'no-code';
  const fields = body as Record<string, unknown>;
  const candidate = fields.code ?? fields.name;
  if (typeof candidate !== 'string') return 'no-code';
  return /^[A-Za-z0-9_]{1,32}$/.test(candidate) ? candidate : 'no-code';
}

/**
 * Read a provider's error body without ever letting it become a log line.
 *
 * Returns only the status and a shape-checked code.
 */
async function describeFailure(response: Response): Promise<string> {
  let code = 'no-code';
  try {
    code = safeCode(await response.json());
  } catch {
    // A non-JSON body is of no diagnostic use and is certainly not safe to
    // print, so it is dropped rather than parsed further.
  }
  return `status=${response.status} code=${code}`;
}

/**
 * The only logging this module does.
 *
 * Takes an enquiry id and a pre-sanitised detail string. No call to this
 * function is ever given a field of the submission: not the name, not the
 * email, not an answer. An operator who needs the content looks up the id.
 */
function logFailure(leg: string, id: string, detail: string): void {
  console.error(`[contact] ${leg} failed (enquiry ${id}): ${detail}`);
}

/* ---------------------------------------------------------------- the store */

/**
 * Insert the enquiry into Supabase over PostgREST.
 *
 * `Prefer: return=minimal` is not a preference here, it is a requirement. The
 * migration grants `service_role` INSERT and deliberately withholds SELECT, so
 * asking PostgREST to return the inserted row would need a privilege this role
 * does not have and the insert would fail. See the CONSEQUENCE note in
 * `supabase/migrations/20260914120000_create_contact_enquiries.sql`.
 */
async function storeEnquiry(enquiry: Enquiry): Promise<LegStatus> {
  const url = process.env.SUPABASE_URL;
  const serviceRole = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceRole) return 'unconfigured';

  /*
   * This is NOT an SSRF guard, and saying otherwise would overstate it: the
   * endpoint is operator-supplied and no visitor input reaches it. It guards a
   * quieter failure. The service-role key is the project's master credential,
   * and the headers below attach it as a bearer token to whatever host this
   * variable names. A typo, a pasted wrong project URL, or an http:// value
   * sends that credential to that host — in cleartext, in the http case — and
   * the only visible symptom is an enquiry that never arrived.
   *
   * Refusing an unparseable or non-HTTPS value turns a silent credential
   * disclosure into the same honest `unconfigured` path an unset variable
   * already takes, which the visitor sees handled properly.
   *
   * The host is deliberately NOT required to end `.supabase.co`. A self-hosted
   * instance or a custom domain is a legitimate deployment, and forbidding it
   * would be a guess about infrastructure rather than a security property.
   */
  let endpoint: URL;
  try {
    endpoint = new URL(url);
  } catch {
    logFailure('supabase insert', enquiry.id, 'supabase_url_unparseable');
    return 'unconfigured';
  }
  if (endpoint.protocol !== 'https:') {
    logFailure('supabase insert', enquiry.id, 'supabase_url_not_https');
    return 'unconfigured';
  }

  // An unanswered optional question is absent, not empty. Storing `''` would
  // make "answered with nothing" and "not answered" indistinguishable in the
  // table, and the column checks in the migration treat NULL as the absent case.
  const orNull = (value: string) => (value === '' ? null : value);

  try {
    const response = await fetch(`${url.replace(/\/+$/, '')}/rest/v1/contact_enquiries`, {
      method: 'POST',
      headers: {
        // Supabase's gateway authenticates on this header; PostgREST behind it
        // reads the bearer. Both carry the same service-role value.
        'apikey': serviceRole,
        'Authorization': `Bearer ${serviceRole}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal',
      },
      body: JSON.stringify({
        id: enquiry.id,
        name: enquiry.name,
        company: orNull(enquiry.company),
        email: enquiry.email,
        objective: enquiry.objective,
        existing: orNull(enquiry.existing),
        deadline: orNull(enquiry.deadline),
        success: orNull(enquiry.success),
        source: enquiry.source,
      }),
      signal: AbortSignal.timeout(TIMEOUT_MS),
      cache: 'no-store',
    });

    if (!response.ok) {
      logFailure('supabase insert', enquiry.id, await describeFailure(response));
      return 'failed';
    }

    return 'ok';
  } catch (error) {
    // `error` may be a TimeoutError from the abort signal or a network fault.
    // Neither carries submission data, but only the name is taken, to keep the
    // promise that nothing from the body can reach a log by accident.
    const name = error instanceof Error ? error.name : 'unknown';
    logFailure('supabase insert', enquiry.id, `exception=${name}`);
    return 'failed';
  }
}

/* ---------------------------------------------------------------- the email */

/**
 * The answered questions as one readable block, question above answer.
 *
 * Three of the four are optional, so an unanswered question is left out rather
 * than sent as an empty heading: whoever reads the enquiry should see what was
 * said, not what was skipped.
 *
 * This is the function the retired `process` webhook key used to be built from.
 * The key is gone; the rendering it produced is still the clearest way to read
 * an enquiry, so it now builds the notification email instead.
 */
function transcript(enquiry: Enquiry): string {
  return QUESTIONS.filter(([key]) => enquiry[key] !== '')
    .map(([key, question]) => `${question}\n${enquiry[key]}`)
    .join('\n\n');
}

function emailBody(enquiry: Enquiry, stored: LegStatus): string {
  // When the row did not land, this email is the only copy of the enquiry. Say
  // so at the top, in the one place a human is certain to look, because the
  // alternative is an enquiry that is quietly answered and then lost from the
  // record.
  const warning =
    stored === 'ok'
      ? ''
      : 'WARNING: this enquiry was NOT saved to the database. This email is the ' +
        'only copy of it. Do not delete it, and check the Supabase project.\n\n';

  const company = enquiry.company === '' ? 'Not given' : enquiry.company;

  return (
    `${warning}A new enquiry came in through the contact form.\n\n` +
    `Name: ${enquiry.name}\n` +
    `Company: ${company}\n` +
    `Email: ${enquiry.email}\n\n` +
    `${transcript(enquiry)}\n\n` +
    `--\n` +
    `Reference: ${enquiry.id}\n` +
    `Received: ${enquiry.receivedAt}\n` +
    `Source: ${enquiry.source}\n`
  );
}

/**
 * Notify the enquiries inbox through Resend.
 *
 * `stored` is passed in rather than looked up because the email says something
 * different when it is the only surviving copy of the enquiry.
 */
async function sendNotification(enquiry: Enquiry, stored: LegStatus): Promise<LegStatus> {
  const mailCredential = process.env.RESEND_API_KEY;
  // Resend will only send from a domain verified in the account, so there is no
  // sane default for this and inventing one would produce a provider rejection
  // on the first real send. Absent it, the email half is simply not configured.
  const from = process.env.CONTACT_NOTIFICATION_FROM;

  if (!mailCredential || !from) return 'unconfigured';

  /*
   * Header-safe interpolation, added 2026-09-14 after a security review.
   *
   * THE DEFECT THIS CLOSES. `name` and `company` arrive here having passed
   * `.trim()` and a length ceiling in actions.ts, and nothing else. `.trim()`
   * removes leading and trailing whitespace; INTERIOR control characters
   * survive. A submission whose name carries a carriage return and line feed
   * followed by "Bcc: someone@example.test" passes validation — non-empty,
   * under 120 characters — and is interpolated straight into the `subject`
   * field below. If Resend does not itself strip those when composing the MIME
   * header, that injects an arbitrary header into a message sent from a domain
   * verified to this company: silent copying of every enquiry to a third party,
   * or spoofed mail carrying our sending reputation.
   *
   * WHY THE EXISTING REASONING DID NOT COVER IT. The note on `reply_to` below
   * argues that field is safe because "there is no header to inject a newline
   * into, and the address has already passed validation". Both halves are
   * correct FOR reply_to — `isEmail` in actions.ts rejects whitespace, so no
   * line break can reach it. The reasoning was never extended to `subject`,
   * which is free text and has no such filter.
   *
   * AND WHY IT IS NOT LEFT TO THE PROVIDER. Whether Resend strips these is
   * plausible and unverified: CONTACT-FORM-SETUP.md and DEPENDENCIES.md both
   * record that its API reference could not be reached from the build
   * environment. A mitigation nobody here has read is not a control this
   * repository owns.
   *
   * SUBJECT ONLY. The email body is a text part, not a header, and the stored
   * row is the record. Sanitising either would mangle genuine enquiries to fix
   * a header problem that does not exist in them.
   *
   * Filtered by CODEPOINT rather than by a regex escape, deliberately. Writing
   * this as a character class cost an hour: the escape sequences were
   * interpreted before they reached the file and went in as literal NUL and
   * 0x1F BYTES, which is not something a .ts file should contain and not
   * something a reader can see. Codepoints cannot be mangled that way and say
   * plainly what is being removed.
   */
  const headerSafe = (value: string) =>
    Array.from(value)
      .map(character => {
        const code = character.codePointAt(0) ?? 0;
        return code < 32 || code === 127 ? ' ' : character;
      })
      .join('')
      .replace(/\s+/g, ' ')
      .trim();

  const safeName = headerSafe(enquiry.name);
  const safeCompany = headerSafe(enquiry.company);

  const subject =
    safeCompany === ''
      ? `New contact enquiry: ${safeName}`
      : `New contact enquiry: ${safeName}, ${safeCompany}`;

  const payload: Record<string, unknown> = {
    from,
    // The destination is the company's published enquiries address, read from
    // the single source of truth rather than repeated here.
    to: [contactEmail],
    subject,
    text: emailBody(enquiry, stored),
    // Replying to the notification replies to the visitor. Safe to take from
    // the submission: this is a JSON API, so there is no header to inject a
    // newline into, and the address has already passed validation.
    reply_to: enquiry.email,
  };

  const send = async (body: Record<string, unknown>) =>
    fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${mailCredential}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(TIMEOUT_MS),
      cache: 'no-store',
    });

  try {
    let response = await send(payload);

    // `reply_to` is the one field name in this module that could not be checked
    // against a primary source while it was written: this environment has no
    // access to Resend's API reference, and the package that would have settled
    // it could not be installed (see DEPENDENCIES.md). The HTTP API is
    // snake_case where the Node SDK is camelCase, so `reply_to` is the expected
    // spelling - but an unverified field name should not be allowed to cost a
    // notification. A 422 is Resend's schema rejection, so on one we drop the
    // field and send the enquiry anyway; the address is in the body regardless.
    //
    // DELETE THIS BRANCH once a real send has confirmed the field. The log line
    // below is how you find out that it was needed.
    if (response.status === 422) {
      logFailure('resend send', enquiry.id, 'status=422 retrying without reply_to');
      const { reply_to: _dropped, ...withoutReplyTo } = payload;
      response = await send(withoutReplyTo);
    }

    if (!response.ok) {
      logFailure('resend send', enquiry.id, await describeFailure(response));
      return 'failed';
    }

    return 'ok';
  } catch (error) {
    const name = error instanceof Error ? error.name : 'unknown';
    logFailure('resend send', enquiry.id, `exception=${name}`);
    return 'failed';
  }
}

/* ------------------------------------------------------------------ deliver */

/**
 * Store the enquiry, then notify - and always attempt both.
 *
 * ORDER, AND WHY BOTH ALWAYS RUN.
 *
 * The store runs first so that the email can tell its reader whether a durable
 * copy exists. A failure in the store does NOT skip the email, and that is the
 * important half of this function: the two halves fail for unrelated reasons,
 * and an enquiry that reaches a human inbox is honoured even when the database
 * refused it. Making the notification conditional on the insert would turn one
 * provider's outage into a lost enquiry.
 *
 * The two failures are not equally bad, and the design follows from which is
 * worse. An enquiry emailed but not stored is missing from the record, but it
 * is sitting in front of a person who will answer it. An enquiry stored but not
 * emailed is safe and invisible: nothing tells anyone it arrived, so it waits
 * until somebody happens to open the table, which may be never. The silent one
 * is worse, so the notification is the leg that gets the loud treatment - it is
 * never skipped, and its failure is always logged as an operational fault even
 * though the visitor is told, correctly, that the enquiry was received.
 *
 * This function reports only what happened. What the visitor is told is the
 * caller's decision, and it lives in `src/app/contact/actions.ts`.
 */
export async function deliverEnquiry(enquiry: Enquiry): Promise<DeliveryOutcome> {
  const store = await storeEnquiry(enquiry);
  const email = await sendNotification(enquiry, store);

  return { store, email };
}
