// GENERATED by gen_archive_content.py - do not hand-edit.
import type { ArchiveBlock } from './types';
import b_best_ai_chatbot_development_services_company from './best-ai-chatbot-development-services-company';
import b_use_ai_in_transportation from './use-ai-in-transportation';
import b_blockchain_application_development_blueprint_plan from './blockchain-application-development-blueprint-plan';
import b_how_much_software_development_costs from './how-much-software-development-costs';
import b_high_impact_ai_business_solutions from './high-impact-ai-business-solutions';
import b_enterprise_blockchain_solutions_reshape_business from './enterprise-blockchain-solutions-reshape-business';
import b_how_to_start_an_ai_business_in_2025 from './how-to-start-an-ai-business-in-2025';
import b_generative_ai_vs_conversational_ai from './generative-ai-vs-conversational-ai';
import b_cryptocurrency_exchange_development_features_costs_and_tips from './cryptocurrency-exchange-development-features-costs-and-tips';
import b_10_profitable_ai_saas_ideas_to_build_right_now from './10-profitable-ai-saas-ideas-to-build-right-now';
import b_10_features_for_nft_marketplace_development_plan from './10-features-for-nft-marketplace-development-plan';
import b_beginners_guide_to_cryptocurrency_wallet_development from './beginners-guide-to-cryptocurrency-wallet-development';
import b_how_to_apply_blockchain_in_development_of_finance_apps from './how-to-apply-blockchain-in-development-of-finance-apps';
import b_why_choose_dapp_development_company_blockchain_solutions from './why-choose-dapp-development-company-blockchain-solutions';
import b_why_businesses_should_adopt_blockchain_accounting from './why-businesses-should-adopt-blockchain-accounting';
import b_what_is_enterprise_conversational_ai_guide_a_non_technical_guide from './what-is-enterprise-conversational-ai-guide-a-non-technical-guide';
import b_ui_ux_design_role_in_ecommerce_development_sales from './ui-ux-design-role-in-ecommerce-development-sales';
import b_top_tools_to_develop_a_scalable_supply_chain_intelligence_platform from './top-tools-to-develop-a-scalable-supply-chain-intelligence-platform';
import b_top_5_ai_data_analytics_tools_for_enterprises_in_2025 from './top-5-ai-data-analytics-tools-for-enterprises-in-2025';
import b_steps_software_development_process from './steps-software-development-process';
import b_natural_language_processing_techniques_for_ai_development from './natural-language-processing-techniques-for-ai-development';
import b_key_challenges_in_iot_app_development from './key-challenges-in-IoT-app-development';
import b_how_to_use_ai_in_web_development from './how-to-use-ai-in-web-development';
import b_how_to_build_ai_model from './how-to-build-AI-model';
import b_how_does_a_block_of_data_on_blockchain_get_locked from './how-does-a-block-of-data-on-blockchain-get-locked';
import b_hashgraph_vs_blockchain_comparison from './hashgraph-vs-blockchain-comparison';
import b_custom_software_solutions_vs_off_the_shelf_software from './custom-software-solutions-vs-off-the-shelf-software';
import b_custom_ai_solutions_vs_pre_built_ai_comparison from './custom-ai-solutions-vs-pre-built-ai-comparison';
import b_cryptographic_hashing_blockchain_development_safety from './cryptographic-hashing-blockchain-development-safety';
import b_building_business_using_blockchain_guide_for_entrepreneurs from './building-business-using-blockchain-guide-for-entrepreneurs';
import b_blockchain_development_trends_2025 from './blockchain-development-trends-2025';
import b_benefits_of_it_managed_support_services_for_remote_teams from './benefits-of-IT-managed-support-services-for-remote-teams';
import b_aiops_use_cases_in_it_operations from './aiops-use-cases-in-it-operations';
import b_agile_vs_waterfall_methodologies_for_custom_software_solutions from './agile-vs-waterfall-methodologies-for-custom-software-solutions';
import b_ar_vs_vr_development_explained from './ar-vs-vr-development-explained';
import b_how_to_make_a_mobile_app_that_earns_real_money from './how-to-make-a-mobile-app-that-earns-real-money';

/**
 * Block bodies for the migrated archive, keyed by slug.
 *
 * SEPARATE FROM THE METADATA so the archive index page can list 36 articles
 * without reaching for 53,000 words of prose to do it. The article route pulls a
 * single entry; the index route touches this module not at all.
 */
export const ARCHIVE_BODIES: Record<string, ArchiveBlock[]> = {
  "best-ai-chatbot-development-services-company": b_best_ai_chatbot_development_services_company,
  "use-ai-in-transportation": b_use_ai_in_transportation,
  "blockchain-application-development-blueprint-plan": b_blockchain_application_development_blueprint_plan,
  "how-much-software-development-costs": b_how_much_software_development_costs,
  "high-impact-ai-business-solutions": b_high_impact_ai_business_solutions,
  "enterprise-blockchain-solutions-reshape-business": b_enterprise_blockchain_solutions_reshape_business,
  "how-to-start-an-ai-business-in-2025": b_how_to_start_an_ai_business_in_2025,
  "generative-ai-vs-conversational-ai": b_generative_ai_vs_conversational_ai,
  "cryptocurrency-exchange-development-features-costs-and-tips": b_cryptocurrency_exchange_development_features_costs_and_tips,
  "10-profitable-ai-saas-ideas-to-build-right-now": b_10_profitable_ai_saas_ideas_to_build_right_now,
  "10-features-for-nft-marketplace-development-plan": b_10_features_for_nft_marketplace_development_plan,
  "beginners-guide-to-cryptocurrency-wallet-development": b_beginners_guide_to_cryptocurrency_wallet_development,
  "how-to-apply-blockchain-in-development-of-finance-apps": b_how_to_apply_blockchain_in_development_of_finance_apps,
  "why-choose-dapp-development-company-blockchain-solutions": b_why_choose_dapp_development_company_blockchain_solutions,
  "why-businesses-should-adopt-blockchain-accounting": b_why_businesses_should_adopt_blockchain_accounting,
  "what-is-enterprise-conversational-ai-guide-a-non-technical-guide": b_what_is_enterprise_conversational_ai_guide_a_non_technical_guide,
  "ui-ux-design-role-in-ecommerce-development-sales": b_ui_ux_design_role_in_ecommerce_development_sales,
  "top-tools-to-develop-a-scalable-supply-chain-intelligence-platform": b_top_tools_to_develop_a_scalable_supply_chain_intelligence_platform,
  "top-5-ai-data-analytics-tools-for-enterprises-in-2025": b_top_5_ai_data_analytics_tools_for_enterprises_in_2025,
  "steps-software-development-process": b_steps_software_development_process,
  "natural-language-processing-techniques-for-ai-development": b_natural_language_processing_techniques_for_ai_development,
  "key-challenges-in-IoT-app-development": b_key_challenges_in_iot_app_development,
  "how-to-use-ai-in-web-development": b_how_to_use_ai_in_web_development,
  "how-to-build-AI-model": b_how_to_build_ai_model,
  "how-does-a-block-of-data-on-blockchain-get-locked": b_how_does_a_block_of_data_on_blockchain_get_locked,
  "hashgraph-vs-blockchain-comparison": b_hashgraph_vs_blockchain_comparison,
  "custom-software-solutions-vs-off-the-shelf-software": b_custom_software_solutions_vs_off_the_shelf_software,
  "custom-ai-solutions-vs-pre-built-ai-comparison": b_custom_ai_solutions_vs_pre_built_ai_comparison,
  "cryptographic-hashing-blockchain-development-safety": b_cryptographic_hashing_blockchain_development_safety,
  "building-business-using-blockchain-guide-for-entrepreneurs": b_building_business_using_blockchain_guide_for_entrepreneurs,
  "blockchain-development-trends-2025": b_blockchain_development_trends_2025,
  "benefits-of-IT-managed-support-services-for-remote-teams": b_benefits_of_it_managed_support_services_for_remote_teams,
  "aiops-use-cases-in-it-operations": b_aiops_use_cases_in_it_operations,
  "agile-vs-waterfall-methodologies-for-custom-software-solutions": b_agile_vs_waterfall_methodologies_for_custom_software_solutions,
  "ar-vs-vr-development-explained": b_ar_vs_vr_development_explained,
  "how-to-make-a-mobile-app-that-earns-real-money": b_how_to_make_a_mobile_app_that_earns_real_money,
};
