// GENERATED by gen_archive_content.py - do not hand-edit.
// Migrated from the previous Pixelette Technologies site, text only.

/**
 * The archive: 36 articles published on the previous site between 2025-03-03
 * and 2025-07-04, carried over so that links to them resolve and the writing is
 * not lost.
 *
 * WHY THESE ARE NOT `Insight` ENTRIES. content/insights.ts models the editorial
 * pipeline the founder's brief describes, and its rule is that a published entry
 * is one Pixelette has written, dated and stands behind as current thinking.
 * These are neither current nor commissioned: they are historical material with
 * their own authors and their own 2025 dates. Folding them into that array would
 * flip the hub's "nothing published yet" state to "36 articles published" and
 * flood a filter bar built for six live categories - which is precisely the
 * inflation §17 forbids. They therefore have their own type, their own index
 * page, and the archive section of the hub (§9) as their entry point.
 *
 * DATES ARE THE ORIGINAL PUBLICATION DATES, untouched. Every article is marked
 * historical where it is displayed.
 *
 * AUTHORS ARE THE REAL BYLINES from the previous site. Six people wrote these;
 * none of them is invented and none is replaced with a house credit.
 */
export type ArchiveGroupId =
  | "artificial-intelligence"
  | "blockchain-web3"
  | "software-development"
  | "mobile-web-design";

export type ArchiveArticle = {
  slug: string;
  title: string;
  summary: string;
  author: string;
  /** ISO. The ORIGINAL publication date. Never moved forward. */
  publishedOn: string;
  readingMinutes: number;
  group: ArchiveGroupId;
};

/** The previous site's own four categories, in size order. */
export const ARCHIVE_GROUPS: readonly { id: ArchiveGroupId; label: string }[] = [
  { id: "artificial-intelligence", label: "AI and machine learning" },
  { id: "blockchain-web3", label: "Blockchain and Web3" },
  { id: "software-development", label: "Software development" },
  { id: "mobile-web-design", label: "Mobile and web design" },
];

/** Newest first. */
export const archiveArticles: ArchiveArticle[] = [
  {
    slug: "best-ai-chatbot-development-services-company",
    title: "Best AI Chatbot Development Service Providers (2025)",
    summary: "Searching for the best AI chatbot development services in 2025? Compare the top 10 providers, their industry expertise, key features, and pricing.",
    author: "Aimun Cheema",
    publishedOn: "2025-07-04",
    readingMinutes: 11,
    group: "artificial-intelligence",
  },
  {
    slug: "use-ai-in-transportation",
    title: "AI in Transportation: How It Works, Benefits & Industry Applications",
    summary: "Explore how AI works in transportation, its key benefits, real-world use cases, and how it's shaping the future of mobility.",
    author: "Sara Illahi Panhwar",
    publishedOn: "2025-07-02",
    readingMinutes: 7,
    group: "artificial-intelligence",
  },
  {
    slug: "blockchain-application-development-blueprint-plan",
    title: "The Complete Blueprint for Blockchain Application Development",
    summary: "Thinking about building on blockchain? This guide walks you through every step of blockchain app development, from planning to deployment.",
    author: "Aimun Cheema",
    publishedOn: "2025-06-30",
    readingMinutes: 13,
    group: "blockchain-web3",
  },
  {
    slug: "how-much-software-development-costs",
    title: "How Much Does Software Development Cost in 2025?",
    summary: "Looking to get software developed in 2025? See the latest cost breakdowns, from small apps to enterprise solutions, and how to plan your budget wisely.",
    author: "Maryam Aslam",
    publishedOn: "2025-06-27",
    readingMinutes: 12,
    group: "software-development",
  },
  {
    slug: "high-impact-ai-business-solutions",
    title: "10 High-Impact AI Business Solutions to Scale and Save Time",
    summary: "Explore the most effective AI business solutions that help companies save time, cut costs, and drive smarter decision-making across operations.",
    author: "Maryam Aslam",
    publishedOn: "2025-06-27",
    readingMinutes: 8,
    group: "artificial-intelligence",
  },
  {
    slug: "enterprise-blockchain-solutions-reshape-business",
    title: "How Enterprise Blockchain Solutions are Reshaping Business Operations",
    summary: "The future of business runs on blockchain. Find out how enterprise blockchain solutions are improving compliance, scalability and performance across industries.",
    author: "Aimun Cheema",
    publishedOn: "2025-06-27",
    readingMinutes: 9,
    group: "blockchain-web3",
  },
  {
    slug: "how-to-start-an-ai-business-in-2025",
    title: "How to Start an AI Business in 2025",
    summary: "Thinking about how to start an AI business? Learn to validate, build, and launch your business with clarity even if you're not a tech expert. ",
    author: "Aimun Cheema",
    publishedOn: "2025-06-26",
    readingMinutes: 9,
    group: "artificial-intelligence",
  },
  {
    slug: "generative-ai-vs-conversational-ai",
    title: "Generative AI vs Conversational AI: What’s the Real Difference?",
    summary: "Confused about generative AI vs conversational AI? Learn how they differ, where they overlap, and which one is more suitable for your next AI project.",
    author: "Aimun Cheema",
    publishedOn: "2025-06-26",
    readingMinutes: 5,
    group: "artificial-intelligence",
  },
  {
    slug: "cryptocurrency-exchange-development-features-costs-and-tips",
    title: "Cryptocurrency Exchange Development: Features, Cost & Tips",
    summary: "Explore the ins and outs of cryptocurrency exchange development, including core features, realistic costs and pro tips to avoid common mistakes.",
    author: "Faisal Jaswal",
    publishedOn: "2025-06-26",
    readingMinutes: 8,
    group: "blockchain-web3",
  },
  {
    slug: "10-profitable-ai-saas-ideas-to-build-right-now",
    title: "10 Profitable AI SaaS Ideas to Build Right Now",
    summary: "Searching for a scalable AI SaaS idea? Some of these profitable options offer real-world use cases and strong market potential.",
    author: "Maryam Aslam",
    publishedOn: "2025-06-26",
    readingMinutes: 8,
    group: "artificial-intelligence",
  },
  {
    slug: "10-features-for-nft-marketplace-development-plan",
    title: "10 Features to Add in Your NFT Marketplace Development Plan",
    summary: "Don't build outdated NFT platforms. Use this checklist of 10 essential NFT marketplace development features to meet 2025 user expectations.",
    author: "Sara Illahi Panhwar",
    publishedOn: "2025-06-10",
    readingMinutes: 7,
    group: "blockchain-web3",
  },
  {
    slug: "beginners-guide-to-cryptocurrency-wallet-development",
    title: "A Beginner’s Guide to Cryptocurrency Wallet Development",
    summary: "Curious about cryptocurrency wallet development? Learn how wallets work, what to consider, and how to get started with no blockchain experience.",
    author: "Aimun Cheema",
    publishedOn: "2025-06-03",
    readingMinutes: 7,
    group: "blockchain-web3",
  },
  {
    slug: "how-to-apply-blockchain-in-development-of-finance-apps",
    title: "How to Apply Blockchain in Development of Finance Apps",
    summary: "Learn how to apply blockchain in finance app development with real-world examples and technical steps used by fintech leaders like Aave.",
    author: "Faisal Jaswal",
    publishedOn: "2025-06-02",
    readingMinutes: 5,
    group: "blockchain-web3",
  },
  {
    slug: "why-choose-dapp-development-company-blockchain-solutions",
    title: "Why Choose a dApp Development Company for Solutions",
    summary: "Learn why a dApp development company offers the skills, tools and tech you need to build amazing decentralized applications.",
    author: "Aimun Cheema",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "blockchain-web3",
  },
  {
    slug: "why-businesses-should-adopt-blockchain-accounting",
    title: "Why Businesses Should Adopt Blockchain Accounting in 2025",
    summary: "Businesses are adopting blockchain accounting for secure, automated finance. Discover how it improves transparency, audits and financial management.",
    author: "Nabia Hassan Sabzwari",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "blockchain-web3",
  },
  {
    slug: "what-is-enterprise-conversational-ai-guide-a-non-technical-guide",
    title: "What Is Enterprise Conversational AI? A Non-Technical Guide",
    summary: "What is enterprise conversational AI and why are top companies investing in it? Discover the simple answer in this non-technical guide.",
    author: "Sara Illahi Panhwar",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "artificial-intelligence",
  },
  {
    slug: "ui-ux-design-role-in-ecommerce-development-sales",
    title: "The Role of UX/UI Design in E-Commerce Development and Sales",
    summary: "Learn how ecommerce web development with strong UX/UI principles helps reduce cart abandonment and improve customer retention.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "mobile-web-design",
  },
  {
    slug: "top-tools-to-develop-a-scalable-supply-chain-intelligence-platform",
    title: "Top Tools to Develop a Scalable Supply Chain Intelligence Platform",
    summary: "Want to future-proof your business? These supply chain intelligence tools are built for speed, agility, and smart decision-making. Explore now.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    /* The previous site filed this under no category; placed
       by subject, not by their classification. */
    group: "software-development",
  },
  {
    slug: "top-5-ai-data-analytics-tools-for-enterprises-in-2025",
    title: "Top 5 AI Data Analytics Tools for Enterprises in 2025",
    summary: "Looking for the best AI data analytics platforms in 2025? We break down 5 enterprise-grade tools that deliver speed, scale, and smart insights.",
    author: "Faisal Jaswal",
    publishedOn: "2025-05-30",
    readingMinutes: 6,
    group: "artificial-intelligence",
  },
  {
    slug: "steps-software-development-process",
    title: "8 Vital Steps of the Software Development Process",
    summary: "Building software that stands out requires the right approach. Discover the 8 key steps to a smooth and efficient software development process.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "software-development",
  },
  {
    slug: "natural-language-processing-techniques-for-ai-development",
    title: "The NLP Playbook: Essential Techniques for AI Development",
    summary: "Discover how natural processing language techniques drive AI development. Learn to create smarter, more responsive applications with NLP at the core.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "artificial-intelligence",
  },
  {
    slug: "key-challenges-in-IoT-app-development",
    title: "Key Challenges in IoT App Development (And How to Solve Them)",
    summary: "Discover the biggest challenges in IoT application development and learn practical strategies to build secure, scalable, and smart IoT systems",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "mobile-web-design",
  },
  {
    slug: "how-to-use-ai-in-web-development",
    title: "How To Use AI In Web Development",
    summary: "Discover how AI in web development improves design, automates coding & personalizes user experiences to make websites smarter and more efficient.",
    author: "Aimun Cheema",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "artificial-intelligence",
  },
  {
    slug: "how-to-build-AI-model",
    title: "How to Build a Smart AI Model | A Guide for Enterprise & Business",
    summary: "This guide explores how businesses and enterprises can build smart AI models for automation, analytics and innovation. Take AI from concept to reality! ",
    author: "Aimun Cheema",
    publishedOn: "2025-05-30",
    readingMinutes: 14,
    group: "artificial-intelligence",
  },
  {
    slug: "how-does-a-block-of-data-on-blockchain-get-locked",
    title: "How Does a Block of Data on a Blockchain Get Locked?",
    summary: "Discover how data is securely locked on a blockchain through cryptographic hashing and consensus mechanisms like PoW and PoS.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 6,
    group: "blockchain-web3",
  },
  {
    slug: "hashgraph-vs-blockchain-comparison",
    title: "Hashgraph vs Blockchain: Which Technology Will Lead the Future?",
    summary: "The battle of next-gen ledgers: Hashgraph vs Blockchain. In this article, find out which technology holds the key to the future of decentralized networks",
    author: "Sara Illahi Panhwar",
    publishedOn: "2025-05-30",
    readingMinutes: 9,
    group: "blockchain-web3",
  },
  {
    slug: "custom-software-solutions-vs-off-the-shelf-software",
    title: "Custom Software vs. Off-the-Shelf Software, Explained",
    summary: "Weighing custom software development against off-the-shelf software solutions? Find out which option delivers the best long-term value for your company.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "software-development",
  },
  {
    slug: "custom-ai-solutions-vs-pre-built-ai-comparison",
    title: "Custom AI Solutions vs. Pre-Built AI: The Smarter Investment?",
    summary: "Struggling to choose between custom AI solutions and pre-built AI? This guide breaks down the pros, cons and best use cases to help you decide.",
    author: "Sara Illahi Panhwar",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "artificial-intelligence",
  },
  {
    slug: "cryptographic-hashing-blockchain-development-safety",
    title: "How Cryptographic Hashing Keeps Blockchain Safe",
    summary: "Blockchain’s inherent features like transparency, immutability and mechanisms like proof of work and cryptographic hashes add up to its robust security.",
    author: "Nabia Hassan Sabzwari",
    publishedOn: "2025-05-30",
    readingMinutes: 6,
    group: "blockchain-web3",
  },
  {
    slug: "building-business-using-blockchain-guide-for-entrepreneurs",
    title: "Building Business Using Blockchain: A Guide for Entrepreneurs",
    summary: "Blockchain isn’t just for crypto. In this article, see how entrepreneurs are using it to build scalable, secure, and future-ready businesses.",
    author: "Maryam Aslam",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "blockchain-web3",
  },
  {
    slug: "blockchain-development-trends-2025",
    title: "Best Blockchain Development Trends in 2025",
    summary: "Wish to explore the best blockchain development trends this year? Read about all tech setting the stage for the next generation of decentralized solutions.",
    author: "Aimun Cheema",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "blockchain-web3",
  },
  {
    slug: "benefits-of-IT-managed-support-services-for-remote-teams",
    title: "10 Benefits of IT Managed Support Services for Remote Teams",
    summary: "Remote team drowning in tech issues? Discover why IT managed support services might be your smartest business move yet.",
    author: "Aimun Cheema",
    publishedOn: "2025-05-30",
    readingMinutes: 8,
    group: "software-development",
  },
  {
    slug: "aiops-use-cases-in-it-operations",
    title: "Top 5 AIOps Use Cases Shaping IT Operations in 2025",
    summary: "Drowning in alerts and outages? Discover how AIOps use cases are fixing IT chaos, redefining operations and how to use them to your business' benefit.",
    author: "Nabia Hassan Sabzwari",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "artificial-intelligence",
  },
  {
    slug: "agile-vs-waterfall-methodologies-for-custom-software-solutions",
    title: "Agile vs. Waterfall: What's Best for Custom Software Solutions?",
    summary: "Explore the pros and cons of Agile vs. Waterfall to find out which software development model is best suited for your custom software solutions and goals.",
    author: "Nabia Hassan Sabzwari",
    publishedOn: "2025-05-30",
    readingMinutes: 7,
    group: "software-development",
  },
  {
    slug: "ar-vs-vr-development-explained",
    title: "Choosing the Best Reality: AR vs. VR Apps",
    summary: "Learn how AR and VR apps work, where they shine, and how businesses are using them to engage users like never before.",
    author: "Nabia Hassan Sabzwari",
    publishedOn: "2025-03-28",
    readingMinutes: 7,
    group: "mobile-web-design",
  },
  {
    slug: "how-to-make-a-mobile-app-that-earns-real-money",
    title: "How to Make a Mobile App That Earns Real Money",
    summary: "global revenue expected to surpass $585.70 billion by 2025. Apps like Instagram, Temu and TikTok have captured",
    author: "Hamid Ayub",
    publishedOn: "2025-03-03",
    readingMinutes: 12,
    group: "software-development",
  },
];

export const archiveBySlug = (slug: string): ArchiveArticle | undefined =>
  archiveArticles.find(a => a.slug === slug);

export const ARCHIVE_PATH = '/insights/archive';
