-- ============================================================================
-- Pix T lead capture - founder instruction, 29 September 2026
--
-- "At the start ask for name and email then start chatting ... Lead Scoring
-- Email Alert Store in Supabase."
--
-- Applied by: supabase db push, or pasted whole into the SQL Editor - by the
-- founder. Writing to the live database is his step, not this repository's.
-- Apply it BEFORE deploying the code that uses it. If the code arrives first,
-- src/lib/enquiries.ts stores Pix T enquiries without their score and logs
-- "lead columns missing" rather than losing them, and chat contacts fail to
-- record (the chat itself is unaffected).
--
-- TWO CHANGES:
--   1. contact_enquiries gains four nullable columns for the lead score. The
--      contact form's rows leave them null: only Pix T enquiries are scored.
--   2. A new table, assistant_contacts, holds the name and email a visitor
--      gives Pix T before chatting, so a visitor who leaves before sending an
--      enquiry is not lost. Name, email, source, time. Nothing else: no
--      answers, no transcript, nothing about the device.
--
-- NOT ALLOWED TO GO LIVE BEFORE THE PRIVACY STATEMENT CHANGES. The published
-- Statement says the site does no profiling of individual visitors. See
-- PRIVACY-STATEMENT-DRAFT-PIX-T-LEADS.md and scripts/check-privacy-interlock.mjs.
-- ============================================================================


-- 1. The score on an enquiry -------------------------------------------------

alter table public.contact_enquiries
  add column if not exists lead_ref     uuid,
  add column if not exists lead_score   smallint,
  add column if not exists lead_band    text,
  add column if not exists lead_reasons text[];

-- Constraints are added separately and by name, so a re-run fails loudly on
-- the one that already exists instead of silently skipping all of them - the
-- trap the first migration's check 3b describes. Drop and re-add if needed.
alter table public.contact_enquiries
  add constraint contact_enquiries_lead_score_range
    check (lead_score is null or lead_score between 0 and 100);
alter table public.contact_enquiries
  add constraint contact_enquiries_lead_band_values
    check (lead_band is null or lead_band in ('cold', 'warm', 'hot', 'urgent'));
-- The rules produce at most eight reasons; sixteen leaves room without leaving
-- the column unbounded (security review N5).
alter table public.contact_enquiries
  add constraint contact_enquiries_lead_reasons_size
    check (lead_reasons is null or cardinality(lead_reasons) <= 16);

-- lead_ref is deliberately NOT a foreign key to assistant_contacts. The two
-- rows are written by separate requests, and the contact row can fail to
-- record while the enquiry succeeds. A foreign key would then refuse the
-- enquiry itself, turning a missing convenience link into a lost lead.

comment on column public.contact_enquiries.lead_ref is
  'Pix T only: the assistant_contacts row recorded when this visitor gave a name and email. Not a foreign key, by design.';
comment on column public.contact_enquiries.lead_score is
  'Pix T only: 0-100 from src/lib/lead-score.ts. Orders the inbox; a person decides whether and how to reply.';
comment on column public.contact_enquiries.lead_band is
  'Pix T only: cold, warm, hot or urgent, derived from lead_score and the timeline.';
comment on column public.contact_enquiries.lead_reasons is
  'Pix T only: the scoring rules as they applied, in plain words, for anyone asking why.';


-- 2. Chat contacts -----------------------------------------------------------

create table if not exists public.assistant_contacts (
  -- Generated by the server action, and handed back to Pix T so the enquiry
  -- that may follow can name this row in contact_enquiries.lead_ref.
  id          uuid        primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  name        text        not null,
  email       text        not null,
  source      text        not null default 'pixelettetech.com/assistant',

  -- The same ceilings as contact_enquiries and src/app/contact/actions.ts.
  constraint assistant_contacts_name_length
    check (char_length(name) between 1 and 120),
  constraint assistant_contacts_email_length
    check (char_length(email) between 3 and 200),
  constraint assistant_contacts_source_length
    check (char_length(source) between 1 and 200)
);

comment on table public.assistant_contacts is
  'Name and email given to Pix T before chatting. Contains personal data. UNVERIFIED: anyone can type any name and address, so this is not a marketing list and must not be used as one. Row Level Security is on and no policy exists, by design - the same two controls as contact_enquiries.';

create index if not exists assistant_contacts_created_at_idx
  on public.assistant_contacts (created_at desc);

-- ACCESS CONTROL: identical to contact_enquiries, for the same reasons, which
-- 20260914120000_create_contact_enquiries.sql sets out in full. RLS on with NO
-- policies; every privilege revoked from public, anon and authenticated; the
-- service role may INSERT and nothing else, so the insert must not ask for the
-- row back (src/lib/enquiries.ts sends Prefer: return=minimal).
alter table public.assistant_contacts enable row level security;

revoke all on table public.assistant_contacts from public;
revoke all on table public.assistant_contacts from anon;
revoke all on table public.assistant_contacts from authenticated;

revoke all on table public.assistant_contacts from service_role;
grant insert on table public.assistant_contacts to service_role;


-- ============================================================================
-- WHAT A REVIEWER MUST CHECK
--
-- Written in an environment with no database; unrun, as the first migration
-- was. Run these after applying.
--
-- 1. The four lead columns exist on contact_enquiries. Expect 4 rows.
--      select column_name from information_schema.columns
--       where table_schema = 'public' and table_name = 'contact_enquiries'
--         and column_name like 'lead_%';
--
-- 2. assistant_contacts: RLS on, no policy. Expect rowsecurity = true, 0.
--      select c.relrowsecurity,
--             (select count(*) from pg_policies p
--               where p.schemaname = 'public' and p.tablename = 'assistant_contacts')
--        from pg_class c join pg_namespace n on n.oid = c.relnamespace
--       where n.nspname = 'public' and c.relname = 'assistant_contacts';
--
-- 3. anon and authenticated hold nothing on it. Expect ZERO rows.
--      select grantee, privilege_type from information_schema.role_table_grants
--       where table_schema = 'public' and table_name = 'assistant_contacts'
--         and grantee in ('anon', 'authenticated', 'PUBLIC');
--
-- 4. service_role holds INSERT only. Expect exactly one row, INSERT.
--      select privilege_type from information_schema.role_table_grants
--       where table_schema = 'public' and table_name = 'assistant_contacts'
--         and grantee = 'service_role';
--
-- 5. From outside, with the ANON key, after one real chat contact exists:
--      GET  {SUPABASE_URL}/rest/v1/assistant_contacts?select=*  -> 401, or 200 []. NEVER a row.
--
-- 6. Every CHECK constraint is present (security review N5). A table that
--    already existed before this file ran would skip the ones written inside
--    `create table if not exists` while checks 2-4 still pass. Expect 3 on
--    assistant_contacts and 11 on contact_enquiries (8 original, 3 added here).
--      select conrelid::regclass, count(*) from pg_constraint
--       where conrelid in ('public.assistant_contacts'::regclass, 'public.contact_enquiries'::regclass)
--         and contype = 'c'
--       group by 1;
-- ============================================================================
