-- ============================================================================
-- contact_enquiries — the table behind the form at pixelettetech.com/contact
--
-- Applied by: supabase db push, or pasted whole into the SQL Editor.
-- Safe to re-run, with one caveat added 2026-09-14: re-running does NOT repair
-- a table that already exists. `create table if not exists` no-ops, so the
-- constraints are skipped while the access-control statements still run. See
-- check 3b in the acceptance block at the end.
--
-- WHY THIS IS NOT THE SIBLING'S `leads` TABLE
-- -------------------------------------------
-- ../repo/supabase/migration.sql defines a `leads` table with session ids,
-- a numeric score, a 'cold'|'warm'|'hot'|'urgent' classification, a status,
-- notes and signals. That schema belongs to a chatbot that watches a
-- conversation and grades it. This site has a seven-field form. Copying that
-- shape would create a dozen columns this site never fills and a scoring
-- apparatus nobody asked for, and every one of those empty columns would be a
-- standing invitation to guess at what it meant. This table holds exactly what
-- the form collects, and nothing else.
--
-- WHAT IS DELIBERATELY NOT STORED
-- -------------------------------
--  * No IP address, no user agent, no fingerprint of any kind. The form does
--    not need them to do its job, so collecting them would be processing
--    personal data without a purpose (UK GDPR Art. 5(1)(c), data minimisation).
--  * No honeypot value. A submission that fills the hidden `website` field is
--    dropped by the server action and never reaches this table.
--  * No `process` transcript column. See the note on that key in
--    src/app/contact/actions.ts: it was a compatibility key for an off-repo
--    webhook consumer that is being retired with the webhook. It held a
--    rendering of the four answers below, so as a column it would be
--    duplicated personal data that can silently drift out of step with the
--    columns it duplicates.
-- ============================================================================

create table if not exists public.contact_enquiries (
  -- Generated by the server action rather than defaulted here, so that the
  -- same id can be written to the server log the moment the row is attempted.
  -- That log line is how an operator finds this row without any personal data
  -- ever being logged. The default stays as a backstop.
  id          uuid        primary key default gen_random_uuid(),

  -- The database's own clock, not the application's. There is deliberately no
  -- second, app-supplied timestamp column: two near-identical times invite the
  -- question of which one is true. The notification email carries its own
  -- send-time in its body; this column is the record.
  created_at  timestamptz not null default now(),

  name        text        not null,
  company     text,
  email       text        not null,

  -- The four qualifying questions, in the order the form asks them. Only the
  -- first is required. The column comments below carry each question verbatim,
  -- so the Supabase table editor shows a reader what was actually asked.
  objective   text        not null,
  existing    text,
  deadline    text,
  success     text,

  source      text        not null default 'pixelettetech.com/contact',

  -- Length ceilings mirror MAX in src/app/contact/actions.ts. The server action
  -- already rejects anything longer with a field-keyed error; this is the
  -- second line, because a constraint in the database is the only one that
  -- holds for a caller that is not the server action.
  constraint contact_enquiries_name_length
    check (char_length(name) between 1 and 120),
  constraint contact_enquiries_company_length
    check (company is null or char_length(company) <= 160),
  constraint contact_enquiries_email_length
    check (char_length(email) between 3 and 200),
  constraint contact_enquiries_objective_length
    check (char_length(objective) between 1 and 4000),
  constraint contact_enquiries_existing_length
    check (existing is null or char_length(existing) <= 4000),
  constraint contact_enquiries_deadline_length
    check (deadline is null or char_length(deadline) <= 200),
  constraint contact_enquiries_success_length
    check (success is null or char_length(success) <= 4000),
  constraint contact_enquiries_source_length
    check (char_length(source) between 1 and 200)
);

comment on table public.contact_enquiries is
  'Enquiries submitted through the contact form on pixelettetech.com. Contains personal data (name, work email, free text). Row Level Security is on and no policy exists, by design - see the migration that created this table.';

comment on column public.contact_enquiries.objective is
  'Form question 1 (required): "What are you trying to build or change?"';
comment on column public.contact_enquiries.existing is
  'Form question 2 (optional): "What exists today?"';
comment on column public.contact_enquiries.deadline is
  'Form question 3 (optional): "Is there a deadline?"';
comment on column public.contact_enquiries.success is
  'Form question 4 (optional): "What would a successful result look like?"';
comment on column public.contact_enquiries.source is
  'Which surface produced the enquiry. One form writes here today; the column '
  'exists so a second one never has to be told apart by guesswork.';

-- The only query anyone realistically runs against this table is "show me the
-- newest enquiries". One index, matching that.
create index if not exists contact_enquiries_created_at_idx
  on public.contact_enquiries (created_at desc);


-- ============================================================================
-- ACCESS CONTROL
--
-- Read this before changing anything below it.
--
-- This table is a list of named individuals and their work email addresses.
-- The anon key that authorises PostgREST requests is published in the browser
-- on any site that uses one - it is designed to be public, and it is not a
-- secret. So the only thing standing between this table and the open internet
-- is what the `anon` role is allowed to do. The answer has to be: nothing.
--
-- There are TWO independent controls here, and they are independent on purpose.
-- Either one alone would be enough today. Both are present so that a future
-- mistake in one does not open the table.
--
--   CONTROL 1 - Row Level Security, enabled with NO POLICIES.
--     With RLS on, a role that does not bypass RLS can only reach rows that
--     some policy permits. There are no policies, so there are no such rows,
--     for anybody, for select, insert, update or delete alike. RLS defaults to
--     deny; the absence of a policy below is the security control, not an
--     omission. DO NOT "finish" this migration by adding a policy.
--
--   CONTROL 2 - table privileges revoked from anon and authenticated.
--     Supabase ships ALTER DEFAULT PRIVILEGES granting ALL on new tables in
--     `public` to anon and authenticated. A table created here is therefore
--     granted to those roles unless something takes it away. The revokes below
--     take it away. This is what makes Control 1 belt-and-braces rather than
--     load-bearing: even if somebody later adds a permissive policy, these
--     roles hold no privilege to exercise it with.
--
-- Writes are the service role's alone. `service_role` holds BYPASSRLS, so it is
-- unaffected by Control 1 - but BYPASSRLS bypasses POLICIES, not PRIVILEGES,
-- which is why it still needs the explicit grant below. Its key is a secret,
-- lives only in the server environment, and is used only by the server action.
-- ============================================================================

alter table public.contact_enquiries enable row level security;

-- NOT `force row level security`, and that is a decision rather than an
-- oversight. FORCE subjects the table OWNER to policies too. With no policies
-- present, forcing it would lock the owning role out of the table, and the
-- owning role is how the founder reads his own enquiries in the Supabase table
-- editor. That would look exactly like data loss. The owner bypassing RLS is
-- the intended behaviour here; the roles that must be kept out are anon and
-- authenticated, and they are kept out by both controls above.

-- Control 2. Written as separate statements rather than one comma-separated
-- revoke so that a reader can see each role named, and so that a role missing
-- in some future Supabase project fails one line instead of all of them.
revoke all on table public.contact_enquiries from public;
revoke all on table public.contact_enquiries from anon;
revoke all on table public.contact_enquiries from authenticated;

-- Least privilege for the one role that is allowed in. The revoke first is
-- deliberate: Supabase's default privileges would otherwise have already
-- granted service_role SELECT, UPDATE and DELETE, none of which the server
-- action uses or should be able to perform.
revoke all on table public.contact_enquiries from service_role;
grant insert on table public.contact_enquiries to service_role;

-- CONSEQUENCE, and it is load-bearing: service_role has INSERT and NOT SELECT,
-- so the insert must not ask for the row back. src/lib/enquiries.ts sends
-- `Prefer: return=minimal` for exactly this reason. An insert that asks
-- PostgREST to return the inserted representation needs SELECT as well and
-- will fail here with a permission error. If a future admin surface needs to
-- list enquiries through the API, grant SELECT explicitly and knowingly:
--     grant select on table public.contact_enquiries to service_role;


-- ============================================================================
-- WHAT A REVIEWER MUST CHECK
--
-- None of the above was executed when it was written: this file was authored in
-- an environment with no database and no Supabase project, so the statements
-- are unrun and the behaviour described is reasoned from PostgreSQL's and
-- Supabase's documented semantics, not observed. Treat the four queries below
-- as the acceptance test, and run them against the project after applying.
--
-- 1. RLS is on, and no policy exists. Expect rowsecurity = true, policies = 0.
--
--      select c.relrowsecurity as rowsecurity,
--             (select count(*) from pg_policies p
--               where p.schemaname = 'public'
--                 and p.tablename  = 'contact_enquiries') as policies
--        from pg_class c
--        join pg_namespace n on n.oid = c.relnamespace
--       where n.nspname = 'public' and c.relname = 'contact_enquiries';
--
-- 2. anon and authenticated hold NO privilege. Expect ZERO rows.
--
--      select grantee, privilege_type
--        from information_schema.role_table_grants
--       where table_schema = 'public'
--         and table_name   = 'contact_enquiries'
--         and grantee in ('anon', 'authenticated', 'PUBLIC');
--
-- 3. service_role holds INSERT and nothing else. Expect exactly one row,
--    INSERT.
--
--      select privilege_type
--        from information_schema.role_table_grants
--       where table_schema = 'public'
--         and table_name   = 'contact_enquiries'
--         and grantee      = 'service_role';
--
-- 3b. The eight CHECK constraints exist. Expect 8 rows.
--
--     Added 2026-09-14, because the header's claim that every statement is
--     idempotent is true statement-by-statement and FALSE as a guarantee about
--     the resulting schema. If this table already exists in any form - created
--     by hand, or by an earlier draft of this file - then `create table if not
--     exists` silently does nothing and the constraints below it are never
--     applied, while the RLS and REVOKE statements further down DO run. The
--     result passes checks 1, 2 and 3 and looks fully configured, with the
--     second line of length defence simply absent. That second line is the only
--     one that holds for a caller which is not the server action, which is
--     precisely when it matters.
--
--       select conname from pg_constraint
--        where conrelid = 'public.contact_enquiries'::regclass
--          and contype  = 'c';
--
--     Fewer than 8 means the table predates this file. Do not "fix" it by
--     re-running this migration - it will no-op again. Add the missing
--     constraints explicitly, or drop and recreate the table if it holds no
--     real enquiries.
--
-- 4. The end-to-end check, and the one that actually matters, because 1-3 read
--    the same catalogues this file wrote to. Do this from outside the database,
--    against the project's REST endpoint, using the ANON key - not the service
--    key:
--
--      GET  {SUPABASE_URL}/rest/v1/contact_enquiries?select=*
--             apikey: {anon key}     -> expect 401, or 200 with []. NEVER a row.
--      POST {SUPABASE_URL}/rest/v1/contact_enquiries
--             apikey: {anon key}     -> expect 401/403. NEVER 201.
--
--    Submit one enquiry through the form first, so that there is a row to leak.
--    A GET that returns [] against an empty table proves nothing.
-- ============================================================================
